import type { UtilityExpense,
    FoodHouseholdExpense,
    TransportationExpense,
    HealthExpense,
    HouseMaintenanceExpense,
    FamilyExpense,
    OtherExpense,
    Member
} from "../type/model"

export const UtilitiesData: UtilityExpense[] = [
    {
        id: "1",
        expense: "Utilities",
        name: "Electricity",
        amount: 3250,
        createdAt: "2026-07-01",
        billingStart: "2026-07-01",
        billingEnd: "2026-07-31",
        dueDate: "2026-07-15",
        status: "Paid",
        paymentMethod: "GCash",
        paidAt: "2026-07-12",
        notes: "Paid before the due date.",
    },

    {
        id: "2",
        expense: "Utilities",
        name: "Water",
        amount: 650,
        createdAt: "2026-07-01",
        billingStart: "2026-07-01",
        billingEnd: "2026-07-31",
        dueDate: "2026-07-18",
        status: "Paid",
        paymentMethod: "Cash",
        paidAt: "2026-07-16",
        notes: "Paid in full.",
    },

    {
        id: "3",
        expense: "Utilities",
        name: "Internet",
        amount: 1699,
        createdAt: "2026-07-01",
        billingStart: "2026-06-25",
        billingEnd: "2026-07-24",
        dueDate: "2026-07-20",
        status: "Overdue",
        notes: "Payment is still pending.",
    },

    {
        id: "4",
        expense: "Utilities",
        name: "MobileLoad",
        amount: 300,
        createdAt: "2026-07-01",
        billingStart: "2026-07-01",
        billingEnd: "2026-07-31",
        dueDate: "2026-07-22",
        status: "Paid",
        paymentMethod: "Maya",
        paidAt: "2026-07-21",
        notes: "Monthly mobile load.",
    },

    {
        id: "5",
        expense: "Utilities",
        name: "MineralWater",
        amount: 240,
        createdAt: "2026-07-01",
        billingStart: "2026-07-01",
        billingEnd: "2026-07-31",
        dueDate: "2026-07-25",
        status: "Pending",
        notes: "Scheduled for payment.",
    },

    {
        id: "6",
        expense: "Utilities",
        name: "CookingGas",
        amount: 1120,
        createdAt: "2026-07-01",
        billingStart: "2026-07-01",
        billingEnd: "2026-07-31",
        dueDate: "2026-07-25",
        status: "Paid",
        paymentMethod: "Cash",
        paidAt: "2026-07-24",
        notes: "Gas cylinder refill.",
    },
];

export const FoodHouseholdData: FoodHouseholdExpense[] = [
    {
        id: "7",
        expense: "FoodAndHousehold",
        type: "Food",
        category: "Groceries",
        name: "Assorted Groceries",
        amount: 2500,
        createdAt: "2026-07-01",
        purchaseDate: "2026-07-26",
        paymentMethod: "Cash",
        notes: "Various grocery items for the household.",
    },
    {
        id: "8",
        expense: "FoodAndHousehold",
        type: "Household",
        category: "Cleaning",
        name: "Dishwashing Liquid",
        amount: 850,
        createdAt: "2026-07-01",
        purchaseDate: "2026-07-24",
        paymentMethod: "GCash",
        notes: "For daily kitchen use.",
    },
    {
        id: "9",
        expense: "FoodAndHousehold",
        type: "Food",
        category: "Groceries",
        name: "Rice",
        amount: 1200,
        createdAt: "2026-07-01",
        purchaseDate: "2026-07-22",
        paymentMethod: "Cash",
        notes: "Monthly rice supply.",
    },
    {
        id: "10",
        expense: "FoodAndHousehold",
        type: "Food",
        category: "Meat",
        name: "Pork",
        amount: 950,
        createdAt: "2026-07-01",
        purchaseDate: "2026-07-20",
        notes: "Bought for family meals.",
    },
    {
        id: "11",
        expense: "FoodAndHousehold",
        type: "Food",
        category: "Fruits",
        name: "Banana",
        amount: 450,
        createdAt: "2026-07-01",
        purchaseDate: "2026-07-18",
        notes: "Fresh bananas from the market.",
    },
    {
        id: "12",
        expense: "FoodAndHousehold",
        type: "Food",
        category: "Snacks",
        name: "Biscuits",
        amount: 350,
        createdAt: "2026-07-01",
        purchaseDate: "2026-07-15",
        paymentMethod: "Cash",
        notes: "Snacks for the household.",
    },
    {
        id: "13",
        expense: "FoodAndHousehold",
        type: "Food",
        category: "Beverages",
        name: "Soft Drinks",
        amount: 500,
        createdAt: "2026-07-01",
        purchaseDate: "2026-07-12",
        paymentMethod: "Maya",
        notes: "For family meals and occasions.",
    },
    {
        id: "14",
        expense: "FoodAndHousehold",
        type: "Household",
        category: "Laundry",
        name: "Laundry Detergent",
        amount: 700,
        createdAt: "2026-07-01",
        purchaseDate: "2026-07-10",
        notes: "Laundry supply for the household.",
    },
    {
        id: "15",
        expense: "FoodAndHousehold",
        type: "Household",
        category: "PersonalCare",
        name: "Shampoo",
        amount: 650,
        createdAt: "2026-07-01",
        purchaseDate: "2026-07-08",
        paymentMethod: "Bank Transfer",
        notes: "Personal care supply.",
    },
    {
        id: "16",
        expense: "FoodAndHousehold",
        type: "Household",
        category: "Kitchen",
        name: "Pan",
        amount: 400,
        createdAt: "2026-07-01",
        purchaseDate: "2026-07-05",
        notes: "Replacement kitchen pan.",
    },
];

export const TransportationData: TransportationExpense[] = [
    {
        id: "17",
        expense: "Transportation",
        category: "Fuel",
        description: "Gasoline",
        amount: 1500,
        createdAt: "2026-07-01",
        date: "2026-07-26",
        paymentMethod: "Cash",
        notes: "Full tank refill.",
    },

    {
        id: "18",
        expense: "Transportation",
        category: "PublicTransport",
        description: "Jeepney Fare",
        amount: 250,
        createdAt: "2026-07-01",
        date: "2026-07-24",
        paymentMethod: "Cash",
        notes: "Daily transportation.",
    },

    {
        id: "19",
        expense: "Transportation",
        category: "Fuel",
        description: "Diesel",
        amount: 1200,
        createdAt: "2026-07-01",
        date: "2026-07-22",
        paymentMethod: "GCash",
        notes: "Diesel refill.",
    },

    {
        id: "20",
        expense: "Transportation",
        category: "PublicTransport",
        description: "Bus Fare",
        amount: 450,
        createdAt: "2026-07-01",
        date: "2026-07-20",
        paymentMethod: "Cash",
        notes: "Bus fare for travel.",
    },

    {
        id: "21",
        expense: "Transportation",
        category: "RideHailing",
        description: "Grab Ride",
        amount: 380,
        createdAt: "2026-07-01",
        date: "2026-07-18",
        paymentMethod: "GCash",
        notes: "Ride-hailing fare.",
    },

    {
        id: "22",
        expense: "Transportation",
        category: "Parking",
        description: "Parking Fee",
        amount: 100,
        createdAt: "2026-07-01",
        date: "2026-07-16",
        paymentMethod: "Cash",
        notes: "Parking fee.",
    },

    {
        id: "23",
        expense: "Transportation",
        category: "Toll",
        description: "Toll Fee",
        amount: 300,
        createdAt: "2026-07-01",
        date: "2026-07-14",
        paymentMethod: "Cash",
        notes: "Toll road fee.",
    },

    {
        id: "24",
        expense: "Transportation",
        category: "VehicleMaintenance",
        description: "Change Oil",
        amount: 1800,
        createdAt: "2026-07-01",
        date: "2026-07-12",
        paymentMethod: "Cash",
        notes: "Regular vehicle maintenance.",
    },

    {
        id: "25",
        expense: "Transportation",
        category: "VehicleMaintenance",
        description: "Car Wash",
        amount: 250,
        createdAt: "2026-07-01",
        date: "2026-07-10",
        paymentMethod: "Cash",
        notes: "Regular car wash.",
    },

    {
        id: "26",
        expense: "Transportation",
        category: "PublicTransport",
        description: "Tricycle Fare",
        amount: 150,
        createdAt: "2026-07-01",
        date: "2026-07-08",
        paymentMethod: "Cash",
        notes: "Local transportation.",
    },
];

export const HealthData: HealthExpense[] = [
    {
        id: "27",
        expense: "Health",
        category: "Medicine",
        description: "Maintenance Medicine",
        amount: 850,
        createdAt: "2026-07-01",
        date: "2026-07-26",
        paymentMethod: "Cash",
        notes: "Monthly maintenance medicine.",
    },

    {
        id: "29",
        expense: "Health",
        category: "Consultation",
        description: "Doctor Consultation",
        amount: 800,
        createdAt: "2026-07-01",
        date: "2026-07-24",
        paymentMethod: "Cash",
        notes: "General medical consultation.",
    },

    {
        id: "30",
        expense: "Health",
        category: "Dental",
        description: "Dental Cleaning",
        amount: 1200,
        createdAt: "2026-07-01",
        date: "2026-07-22",
        paymentMethod: "GCash",
        notes: "Routine dental cleaning.",
    },

    {
        id: "31",
        expense: "Health",
        category: "Laboratory",
        description: "Blood Test",
        amount: 650,
        createdAt: "2026-07-01",
        date: "2026-07-20",
        paymentMethod: "Cash",
        notes: "Laboratory blood test.",
    },

    {
        id: "32",
        expense: "Health",
        category: "Medicine",
        description: "Pain Reliever",
        amount: 250,
        createdAt: "2026-07-01",
        date: "2026-07-18",
        paymentMethod: "Cash",
        notes: "Over-the-counter medicine.",
    },

    {
        id: "33",
        expense: "Health",
        category: "Consultation",
        description: "Follow-up Consultation",
        amount: 500,
        createdAt: "2026-07-01",
        date: "2026-07-15",
        paymentMethod: "GCash",
        notes: "Follow-up medical consultation.",
    },

    {
        id: "34",
        expense: "Health",
        category: "Dental",
        description: "Tooth Extraction",
        amount: 1800,
        createdAt: "2026-07-01",
        date: "2026-07-12",
        paymentMethod: "Cash",
        notes: "Dental extraction procedure.",
    },

    {
        id: "35",
        expense: "Health",
        category: "Laboratory",
        description: "Urinalysis",
        amount: 200,
        createdAt: "2026-07-01",
        date: "2026-07-10",
        paymentMethod: "Cash",
        notes: "Routine laboratory test.",
    },

    {
        id: "36",
        expense: "Health",
        category: "Other",
        description: "First Aid Supplies",
        amount: 450,
        createdAt: "2026-07-01",
        date: "2026-07-08",
        paymentMethod: "Maya",
        notes: "Basic first aid supplies.",
    },
];

export const HouseMaintenanceData: HouseMaintenanceExpense[] = [
    {
        id: "37",
        expense: "HouseMaintenance",
        category: "Repairs",
        description: "Faucet Repair",
        amount: 500,
        createdAt: "2026-08-01",
        date: "2026-07-28",
        paymentMethod: "Cash",
        notes: "Repair for leaking kitchen faucet.",
    },

    {
        id: "38",
        expense: "HouseMaintenance",
        category: "Repairs",
        description: "Light Bulb Replacement",
        amount: 350,
        createdAt: "2026-08-01",
        date: "2026-07-26",
        paymentMethod: "Cash",
        notes: "Replaced damaged light bulbs.",
    },

    {
        id: "39",
        expense: "HouseMaintenance",
        category: "Repairs",
        description: "Door Lock Repair",
        amount: 800,
        createdAt: "2026-08-01",
        date: "2026-07-24",
        paymentMethod: "GCash",
        notes: "Repair and adjustment of door lock.",
    },

    {
        id: "40",
        expense: "HouseMaintenance",
        category: "Cleaning",
        description: "Roof Cleaning",
        amount: 1200,
        createdAt: "2026-08-01",
        date: "2026-07-22",
        paymentMethod: "Cash",
        notes: "Professional roof cleaning service.",
    },

    {
        id: "41",
        expense: "HouseMaintenance",
        category: "PestControl",
        description: "Pest Control Service",
        amount: 1500,
        createdAt: "2026-08-01",
        date: "2026-07-20",
        paymentMethod: "GCash",
        notes: "Scheduled household pest control service.",
    },

    {
        id: "42",
        expense: "HouseMaintenance",
        category: "Maintenance",
        description: "Air Conditioner Service",
        amount: 900,
        createdAt: "2026-08-01",
        date: "2026-07-18",
        paymentMethod: "Cash",
        notes: "Routine air conditioner cleaning and maintenance.",
    },

    {
        id: "43",
        expense: "HouseMaintenance",
        category: "Repairs",
        description: "Clogged Drain Repair",
        amount: 650,
        createdAt: "2026-08-01",
        date: "2026-07-15",
        paymentMethod: "Cash",
        notes: "Cleared and repaired clogged drain.",
    },

    {
        id: "44",
        expense: "HouseMaintenance",
        category: "Repairs",
        description: "Electrical Outlet Repair",
        amount: 750,
        createdAt: "2026-08-01",
        date: "2026-07-12",
        paymentMethod: "GCash",
        notes: "Repaired faulty electrical outlet.",
    },

    {
        id: "45",
        expense: "HouseMaintenance",
        category: "Other",
        description: "Curtain Rod Replacement",
        amount: 450,
        createdAt: "2026-08-01",
        date: "2026-07-10",
        paymentMethod: "Cash",
        notes: "Replaced damaged curtain rod.",
    },
];

export const FamilyExpensesData: FamilyExpense[] = [
    {
        id: "46",
        expense: "FamilyExpenses",
        category: "Education",
        description: "School Supplies",
        amount: 1200,
        createdAt: "2026-08-01",
        date: "2026-07-28",
        paymentMethod: "Cash",
        notes: "School supplies for the new semester.",
    },

    {
        id: "47",
        expense: "FamilyExpenses",
        category: "Allowance",
        description: "Weekly Allowance",
        amount: 1500,
        createdAt: "2026-08-01",
        date: "2026-07-26",
        paymentMethod: "Cash",
        notes: "Weekly family allowance.",
    },

    {
        id: "48",
        expense: "FamilyExpenses",
        category: "Entertainment",
        description: "Family Day Out",
        amount: 1800,
        createdAt: "2026-08-01",
        date: "2026-07-24",
        paymentMethod: "Cash",
        notes: "Family outing expenses.",
    },

    {
        id: "49",
        expense: "FamilyExpenses",
        category: "Entertainment",
        description: "Movie Tickets",
        amount: 1000,
        createdAt: "2026-08-01",
        date: "2026-07-22",
        paymentMethod: "GCash",
        notes: "Movie tickets for the family.",
    },

    {
        id: "50",
        expense: "FamilyExpenses",
        category: "Celebrations",
        description: "Birthday Celebration",
        amount: 3000,
        createdAt: "2026-08-01",
        date: "2026-07-20",
        paymentMethod: "Cash",
        notes: "Food and decorations for the birthday celebration.",
    },

    {
        id: "51",
        expense: "FamilyExpenses",
        category: "Celebrations",
        description: "Fiesta Celebration",
        amount: 5000,
        createdAt: "2026-08-01",
        date: "2026-07-18",
        paymentMethod: "Cash",
        notes: "Food and other fiesta expenses.",
    },

    {
        id: "52",
        expense: "FamilyExpenses",
        category: "Celebrations",
        description: "Christmas Celebration",
        amount: 8000,
        createdAt: "2026-08-01",
        date: "2026-07-15",
        paymentMethod: "Bank Transfer",
        notes: "Christmas food and celebration expenses.",
    },

    {
        id: "53",
        expense: "FamilyExpenses",
        category: "Celebrations",
        description: "New Year Celebration",
        amount: 4500,
        createdAt: "2026-08-01",
        date: "2026-07-12",
        paymentMethod: "GCash",
        notes: "Food and supplies for the New Year celebration.",
    },

    {
        id: "54",
        expense: "FamilyExpenses",
        category: "Education",
        description: "School Project Materials",
        amount: 650,
        createdAt: "2026-08-01",
        date: "2026-07-10",
        paymentMethod: "Cash",
        notes: "Materials for a school project.",
    },

    {
        id: "55",
        expense: "FamilyExpenses",
        category: "Other",
        description: "Family Miscellaneous Expense",
        amount: 500,
        createdAt: "2026-08-01",
        date: "2026-07-08",
        paymentMethod: "Maya",
        notes: "Miscellaneous family expense.",
    },
];

export const OtherExpensesData: OtherExpense[] = [
    {
        id: "56",
        expense: "OtherExpenses",
        category: "Personal",
        description: "Haircut",
        amount: 300,
        createdAt: "2026-08-01",
        date: "2026-07-28",
    },
    {
        id: "57",
        expense: "OtherExpenses",
        category: "Donations",
        description: "Charity Donation",
        amount: 500,
        createdAt: "2026-08-01",
        date: "2026-07-26",
    },
    {
        id: "58",
        expense: "OtherExpenses",
        category: "Subscriptions",
        description: "Streaming Subscription",
        amount: 549,
        createdAt: "2026-08-01",
        date: "2026-07-24",
    },
    {
        id: "59",
        expense: "OtherExpenses",
        category: "Government",
        description: "Government Document Processing",
        amount: 300,
        createdAt: "2026-08-01",
        date: "2026-07-22",
    },
    {
        id: "60",
        expense: "OtherExpenses",
        category: "Miscellaneous",
        description: "Miscellaneous Expense",
        amount: 650,
        createdAt: "2026-08-01",
        date: "2026-07-20",
    },
    {
        id: "61",
        expense: "OtherExpenses",
        category: "Tickets",
        description: "Movie Tickets",
        amount: 800,
        createdAt: "2026-08-01",
        date: "2026-07-18",
    },
    {
        id: "62",
        expense: "OtherExpenses",
        category: "Fees",
        description: "Bank Transaction Fee",
        amount: 100,
        createdAt: "2026-08-01",
        date: "2026-07-15",
    },
    {
        id: "63",
        expense: "OtherExpenses",
        category: "Services",
        description: "Laundry Service",
        amount: 450,
        createdAt: "2026-08-01",
        date: "2026-07-12",
    },
    {
        id: "64",
        expense: "OtherExpenses",
        category: "Personal",
        description: "Personal Care Products",
        amount: 750,
        createdAt: "2026-08-01",
        date: "2026-07-10",
    },
    {
        id: "65",
        expense: "OtherExpenses",
        category: "Subscriptions",
        description: "Cloud Storage Subscription",
        amount: 149,
        createdAt: "2026-08-01",
        date: "2026-07-08",
    },
    {
        id: "66",
        expense: "OtherExpenses",
        category: "Donations",
        description: "Community Donation",
        amount: 1000,
        createdAt: "2026-08-01",
        date: "2026-07-05",
    },
    {
        id: "67",
        expense: "OtherExpenses",
        category: "Tickets",
        description: "Event Ticket",
        amount: 1200,
        createdAt: "2026-08-01",
        date: "2026-07-03",
    },
];

export const MembersData: Member[] = [
    {
        id: "1",
        name: "Jericho Zara",
        familyRole: "Father",
        money: 25000,
        createdAt: "2026-07-01",
    },
    {
        id: "2",
        name: "Lorae Singueo",
        familyRole: "Mother",
        money: 10000,
        createdAt: "2026-07-01",
    },
    {
        id: "3",
        name: "Gojo Zara",
        familyRole: "Son",
        money: 10000,
        createdAt: "2026-07-01",
    },
    {
        id: "4",
        name: "Lucy Zara",
        familyRole: "Daughter",
        money: 5000,
        createdAt: "2026-07-01",
    },
    {
        id: "5",
        name: "Yuji Zara",
        familyRole: "Son",
        money: 0,
        createdAt: "2026-07-01",
    },
];