import type { Metadata } from "next";
import {
  Cinzel,
  Playfair_Display,
  Libre_Baskerville
} from "next/font/google"
import "./globals.css";
import { SidebarProvider } from "./context/sidebarContext";
import { ExpensesSectionProvider }  from "./context/expensesSectionContext";

const cinzel = Cinzel({
  variable: "--font-cinzel",
  subsets: ["latin"],
});

const playfairDisplay = Playfair_Display({
  variable: "--font-playfair-display",
  subsets: ["latin"],
});

const libreBaskerville = Libre_Baskerville({
  variable: "--font-libre-baskerville",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${cinzel.variable} ${playfairDisplay.variable} ${libreBaskerville.variable} h-full antialiased`}
    >
      
      <body className="min-h-full flex flex-col">
        <SidebarProvider>
          <ExpensesSectionProvider>
            {children}
          </ExpensesSectionProvider>
        </SidebarProvider>
      </body>
    </html>
  );
}
